# Generated by Django 5.1.7 on 2025-04-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='isMfaEnabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='secret_key',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
