# Generated by Django 5.1.7 on 2025-05-07 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0002_customuser_ismfaenabled_customuser_secret_key'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
